spring.application.name=tarea4

# Server configuration
server.port=8081


# H2 Database configuration (for testing)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=Bullita3089

# H2 Console (enable for debugging)
spring.h2.console.enabled=true

# JPA configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf configuration
spring.thymeleaf.cache=false
